apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: oracle  # Specifica il namespace qui
  name: oracle-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

