apiVersion: v1
kind: Service
metadata:
  name: oracle-service
spec:
  selector:
    app: oracle-db
  ports:
  - protocol: TCP
    port: 1521
    targetPort: 1521
    nodePort: 31521
  type: NodePort

