apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oracle-binding-role
  namespace: oracle  # Specifica il namespace qui
subjects:
- kind: User
  name: edimatt  # Il nome deve corrispondere al CN del certificato client
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: oracle-reader
  apiGroup: rbac.authorization.k8s.io

